### ISSUE TITLE
document permissioning for functions

### ISSUE THREAD

**Issue by ashishsingal1** [vanna-ai/vanna#10]
we should include who has permission to do this action (eg admin or anyone), for the dataset functions / write functions especially.

**Comment by zainhoda** [comment]
@ashishsingal1 to define the permissioning

**Comment by zainhoda** [comment]
For the purposes of documentation, tried to simplify it into a table:
https://docs.vanna.ai/reference/#vanna--permissions

Since we expect most usage to be via the magic wrapper functions `vn.ask()` and `vn.train()` -- I don't think we need much more than this for now.
