### ISSUE TITLE
Typos in code

### ISSUE THREAD

**Issue by robsonzagrejr** [vanna-ai/vanna#115]
Hello, I'm justing realizing some stuffs that really seems like a typo. I'll try to put here what I find:

- I don't know if [this](https://github.com/vanna-ai/vanna/blob/main/src/vanna/openai_chat.py#L124) in OpenAI_Chat is a typo or a improvement in the context to the model.
- Seems that [here](https://github.com/vanna-ai/vanna/blob/main/src/vanna/openai_embeddings.py#L30) u forgot to change the default `engine` to the one in the config file.

Anyway, just  reporting so u guys can double check :)

**Comment by zainhoda** [comment]
Thank you! You are correct on both counts!

**Comment by robsonzagrejr** [comment]
Glad that I could help some how : )

**Comment by robsonzagrejr** [comment]
So, seems to me that [this](https://github.com/vanna-ai/vanna/blob/main/src/vanna/openai_chat.py#L158) is another typo.
If I'm not wrong just need to change the `engine` to `model` so we can use the `gpt-4` as example right?

**Comment by zainhoda** [comment]
@robsonzagrejr could you try the changes using:
`pip install 'git+https://github.com/vanna-ai/vanna.git@remote#egg=vanna[chromadb,snowflake,openai]'`

```python
from vanna.local import LocalContext_OpenAI

vn = LocalContext_OpenAI({"api_key": "sk-...", "model": "gpt-4"})
```

**Comment by robsonzagrejr** [comment]
@zainhoda it's working fine :) Thanks for the quickly reply.
I just have one question, I didn't manage to find in the code the alteration to make this works... How are u defining the `model` in the `submit_prompt` function?
