### ISSUE TITLE
'DataFrame' object is not callable

### ISSUE THREAD

**Issue by bryanjo28** [vanna-ai/vanna#118]
I have tried to connect vanna to my database using SQL Server. But when I used vn.ask() from my model, it cannot show table from DataFrame. What Should I do?

SELECT * FROM datasetSapi WHERE Ingredients LIKE '%pare%'
Couldn't run sql:  'DataFrame' object is not callable

**Comment by zainhoda** [comment]
Per our discussion, this had to do with how `vn.run_sql` was being set. `vn.run_sql` should be set to any function that takes in SQL as a string and returns a pandas DataFrame.
