### ISSUE TITLE
Ability to access generated SQL when vn.ask fails due to invalid SQL

### ISSUE THREAD

**Issue by scheid** [vanna-ai/vanna#122]
when `vn.ask` generates SQL that is invalid (such as it guesses wrong on a table name or field name/value), it would be nice if that generated sql could still be accessed somehow.  Currently, the overall call to `vn.ask'` throws an exception because of the bad SQL and the generated sql is not accessible.

Maybe you could put the sql string generated during `ask` into a property of `vn` itself, and we could then grab it inside an `except` block, like `vn.generated_ask_sql` ?

The reason for this request is that I am logging all questions and sql from users' calls to `vn.ask` and want to include both successes and failures, so I can handle training the model in a more controlled way than using the `vn.ask` `auto_train=True` param.

**Comment by zainhoda** [comment]
Are you running this as part of an independent Python application? Generally, `vn.ask` is a convenience method meant for when you're running inside a Jupyter notebook. If you have a full-fledged application, then I would recommend using the atomic components and that way you can customize the behavior as you see fit. These are the components inside `vn.ask`:

```python
sql = generate_sql(question=question)

df = vn.run_sql(sql)

# (optional) Insert training here based on heuristics

plotly_code = vn.generate_plotly_code(question=question, sql=sql, df=df)

fig = vn.get_plotly_figure(plotly_code=plotly_code, df=df, dark_mode=False)

followup_questions = vn.generate_followup_questions(question=question, df=df)

```
