### ISSUE TITLE
Why isn't it based on fuzzy queries or how should I optimize my questioning

### ISSUE THREAD

**Issue by dielect** [vanna-ai/vanna#148]
For example: I want to query Bob's information and the training SQL I pass to him is:
```sql
SELECT * from db WHERE nickname like '%Bob%'
```
But when I ask again: what is Bob's message, it is forever given as
```
SELECT * from db WHERE nickname = Bob
```
I'm wondering why he didn't base his query on my training data, since the training data already has the exact matching SQL inside it

**Comment by zainhoda** [comment]
Could you let me know which configuration you're using? 

What would be helpful is how you initialized Vanna. 

Also, what was the exact vn.train statement and the exact question that was asked?

Also, just as a general point, `SELECT *` is not usually a good training query since you're not giving the LLM any information about what columns are available

**Comment by dielect** [comment]
I referenced [documentation](https://vanna.ai/docs/other-database-openai-vanna-vannadb.html) to connect to a `MySQL` database. Below is my rough code:   
```python
import vanna as vn
# set api key ....
vn.set_model('model')
vn.train("SELECT * from db WHERE nickname like '%Bob%'")
```
Then I questioned it:
```python
res = vn.ask(' what is Bob's message?')
```
-----
I just went and looked at the source code for `train` and it seems to ask for a `QUESTION`,is this due to me not providing one? I admit I just read the docs and didn't really look at the source code.


I just re-trained him and I realized that he was able to run as I expected, 
```python
vn.train("what is Bob's message?", sql="SELECT * from db WHERE nickname like '%Bob%'")
```

which was my problem. By the way, does the community offer best practices for training? I guess I'll have to go read up on it

Thank you very much guys.🙏
