### ISSUE TITLE
Root functions will be deprecated

### ISSUE THREAD

**Issue by zainhoda** [vanna-ai/vanna#169]
In order to have a consistent experience regardless of the configuration that you choose, all the root functions will be deprecated:

https://github.com/vanna-ai/vanna/blob/main/src/vanna/__init__.py

The docstrings for each function should be removed. The functions themselves should not be removed -- instead, they should raise an exception with an example of how to transition old code to the new method of:

```python
vn = VannaDefault(model=vanna_model_name, api_key=api_key)
```

The root functions are legacy from a  time before we had multiple configuration options, which are enabled by the `VannaBase` abstract base class. The sample notebooks have already been switched. Now what remains are code samples from third parties, which is why these root functions should raise exceptions so that people can transition more easily.

For now, the remaining function that will stay in the base class will be `get_api_key` for the sake of being able to run the Chinook demo.

**Comment by bryanherger** [comment]
I see that add_user_to_model has been deprecated though it's still documented at https://vanna.ai/docs/vanna.html#add_user_to_model
I am trying to create a new model but get the following:
Exception: ('Error adding documentation', {'error': {'code': -32600, 'message': 'User bherger@opentext.com not in model vertica-demo-1'}, 'jsonrpc': '2.0'})
For my previous model, I added myself with add_user_to_model with admin = True, but that doesn't work now with 0.2.1.  How do I add myself to the new model?

**Comment by zainhoda** [comment]
Hi! Model creation should be done in the UI now
