### ISSUE TITLE
Getting-Started notebook failed with error

### ISSUE THREAD

**Issue by ttkrpink** [vanna-ai/vanna#172]
Strange enough, the getting started notebook failed. NO such table. The sqlite file downloaded has the table with "Artist" instead of the lower case error message.

Any thoughts on fixing it?

![1705912998070](https://github.com/vanna-ai/vanna/assets/2522889/7655e75c-4e12-4796-b82e-ee55974ad806)

**Comment by zainhoda** [comment]
Thanks for reporting! This should be resolved now. The training data somehow got removed from this model.
