### ISSUE TITLE
Is there a very simple tutorial? To train and ask the model?

### ISSUE THREAD

**Issue by ttkrpink** [vanna-ai/vanna#173]
Suppose I have a very simple dataset, all I want to ask is: what's the average age? What's the average salary?

```
name gender    age     salary
a	f	20	100
b	f	30	200
c	m	40	300
d	m	50	400
e	m	60	500
```

It seems that the training needs a question/sql pair. The training example only show sql part but not the sql. There is one comment  [SQLite Training](https://github.com/vanna-ai/vanna/issues/170#issuecomment-1902866520)  that suggests how to add "Documents" to the traning though, but not the question pair.

**Comment by zainhoda** [comment]
Hello —

Which database are you using?

You can go here and pick your database:
https://vanna.ai/docs/snowflake-openai-vanna-vannadb.html

The notebook shows how you can use the database information schema to extract the necessary baseline training data.

**Comment by ttkrpink** [comment]
> Hello —
> 
> 
> 
> Which database are you using?
> 
> 
> 
> You can go here and pick your database:
> 
> https://vanna.ai/docs/snowflake-openai-vanna-vannadb.html
> 
> 
> 
> The notebook shows how you can use the database information schema to extract the necessary baseline training data. 

SQLite. I did try the comment from another post but it only adds documents, not question/SQL pairs.
