### ISSUE TITLE
Add a function to summarize results

### ISSUE THREAD

**Issue by zainhoda** [vanna-ai/vanna#181]
We need to add a function that will summarize the results in natural language.

The function will have to take in the tabular results and/or the chart image.

**Comment by LJH4** [comment]
My solution to the the summarizing the answer using the langchain sql quickstart example https://python.langchain.com/docs/use_cases/sql/quickstart  [ I was confused by the RunnablePassthrough mechanics so commented it out and executed a way I found more intuitive).

from langchain.chat_models import ChatOpenAI
from operator import itemgetter
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
import streamlit as st

os.environ["OPENAI_API_KEY"] =st.secrets.openai.openai_api_key

def ai_summarize_answer(question, sql, df):
    llm= ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo') 
    answer_prompt = PromptTemplate.from_template(
        """Given the following user question, corresponding SQL query, and SQL result, answer the user question.
        If the response cannot be created using the relevant data, provide a response that indicates that a response cannot be found in the relevant data.
        If the list is longer than 5 items, describe the list in a few sentences and always include the number of unique items in the list.   

    Question: {my_question}
    SQL Query: {sql}
    SQL Result: {df}
    Answer: """
    )

    answer = answer_prompt | llm | StrOutputParser()
    
    # chain = (
    #     RunnablePassthrough.assign(query=write_query).assign(
    #         result=itemgetter("query") | execute_query
    #     )
    #     | answer
    # )
    
    summarize_answer=answer.invoke({"my_question": question, "sql": sql, "df": df})
    
    return summarize_answer
