### ISSUE TITLE
To run vanna ai locally, python version above 3.9 is required.

### ISSUE THREAD

**Issue by Kartik1110** [vanna-ai/vanna#185]
Vanna AI throws an error if python version is below 3.8.

Traceback (most recent call last):
  File "/home/user/Code/vanna/vannaAi.py", line 2, in <module>
    from vanna.remote import VannaDefault
  File "/home/user/.local/lib/python3.8/site-packages/vanna/remote.py", line 9, in <module>
    from .base import VannaBase
  File "/home/user/.local/lib/python3.8/site-packages/vanna/base/__init__.py", line 1, in <module>
    from .base import VannaBase
  File "/home/user/.local/lib/python3.8/site-packages/vanna/base/base.py", line 21, in <module>
    class VannaBase(ABC):
  File "/home/user/.local/lib/python3.8/site-packages/vanna/base/base.py", line 56, in VannaBase
    def generate_questions(self, **kwargs) -> list[str]:
  
TypeError: 'type' object is not subscriptable

**Comment by zainhoda** [comment]
What version of Vanna do you have installed?

We started requiring Python 3.9
https://github.com/vanna-ai/vanna/blob/main/pyproject.toml#L14

**Comment by relic-yuexi** [comment]
> Vanna AI throws an error if python version is below 3.8.
> 
> Traceback (most recent call last): File "/home/user/Code/vanna/vannaAi.py", line 2, in from vanna.remote import VannaDefault File "/home/user/.local/lib/python3.8/site-packages/vanna/remote.py", line 9, in from .base import VannaBase File "/home/user/.local/lib/python3.8/site-packages/vanna/base/**init**.py", line 1, in from .base import VannaBase File "/home/user/.local/lib/python3.8/site-packages/vanna/base/base.py", line 21, in class VannaBase(ABC): File "/home/user/.local/lib/python3.8/site-packages/vanna/base/base.py", line 56, in VannaBase def generate_questions(self, **kwargs) -> list[str]:
> 
> TypeError: 'type' object is not subscriptable

just change the 'list' to List , which import from Typing. just this
