### ISSUE TITLE
New parameter: allow_llm_to_see_data

### ISSUE THREAD

**Issue by zainhoda** [vanna-ai/vanna#219]
As we work on new functionality like summarization that requires the ability of the LLM to see the data, we need to introduce a parameter to both vn.ask and the flask run function. This will allow the user to be explicit about whether or not they will allow any part of the database contents to be sent to the LLM. 

By default, this parameter should be False

**Comment by CNouraAraujo** [comment]
Is it possible to add this parameter (allow_llm_to_see_data) to an application developed with Vanna AI and Chainlit?
