### ISSUE TITLE
How to handle embedding model download yourself with ChromaDB client

### ISSUE THREAD

**Issue by andreped** [vanna-ai/vanna#222]
This line of code is causing some headache:
https://github.com/vanna-ai/vanna/blob/8c5e05a89d0280082d37c9ef53fdcda384aa247c/src/vanna/chromadb/chromadb_vector.py#L13

The problem is that if you want to store ChromaDB in a docker container, you most likely want to handle all downloads yourself, and give very limited rights to ChromaDB and Vanna, in terms of what is allowed to write on disk and where. If you try to download the model yourself, at the appropriate place (after reading some ChromaDB source code I found where it was trying to save the model), it will give an error stating that the model is already on disk (this I expected would be fine but this yields an error).

Another problem is that ChromaDB currently also uses PersistentClient, meaning that an `.sqlite3` file will be saved on disk.

**Hence, I would like the following features:**
* Allowing to use in-memory vector database with ChromaDB, hence not saving anything on disk
* Allowing to predownload the embedding model and in turn not requiring ChromaDB to have internet access to work in Vanna

Issue was observed on: Ubuntu 22.04 using `vanna==0.0.36` and Python 3.10.8 (after also fixing the `sqlite3` issue Chroma has for Python 3.10).

**Comment by relic-yuexi** [comment]
just use this:

```python
from chromadb.utils import embedding_functions
# device = "cuda" if torch.cuda.is_available() else "cpu"

bge_embeddingFunction = embedding_functions.SentenceTransformerEmbeddingFunction("/AI-ModelScope/bge-large-zh-v1.5","cuda",normalize_embeddings=True)

config = {"embedding_function":bge_embeddingFunction, "path": "/root/chatdb/chromadb"}
```

**Comment by relic-yuexi** [comment]
in /src/vanna/chromadb/chromadb_vector.py

```python
        if config is not None:
            path = config.get("path", ".")
            self.embedding_function = config.get("embedding_function", default_ef)
        else:
            path = "."
            self.embedding_function = default_ef
```

**Comment by andreped** [comment]
> in /src/vanna/chromadb/chromadb_vector.py
> 
> ```python
>         if config is not None:
>             path = config.get("path", ".")
>             self.embedding_function = config.get("embedding_function", default_ef)
>         else:
>             path = "."
>             self.embedding_function = default_ef
> ```

Sure, I can give it a go and see if it resolves the issue I was observing. But this needs to be added to Vanna itself, as I do not control this logic when using the library. Thanks for the suggestion, @relic-yuexi :]

**Comment by relic-yuexi** [comment]
> > in /src/vanna/chromadb/chromadb_vector.py
> > ```python
> >         if config is not None:
> >             path = config.get("path", ".")
> >             self.embedding_function = config.get("embedding_function", default_ef)
> >         else:
> >             path = "."
> >             self.embedding_function = default_ef
> > ```
> 
> Sure, I can give it a go and see if it resolves the issue I was observing. But this needs to be added to Vanna itself, as I do not control this logic when using the library. Thanks for the suggestion, @relic-yuexi :]

actually i had make a pr for it

**Comment by andreped** [comment]
> actually i had make a pr for it

@relic-yuexi I do not see a PR for this yet. Were you going to make one? If not, I can give it a go, as I have a specific use case I can test it for directly.

**Comment by relic-yuexi** [comment]
> > actually i had make a pr for it
> 
> @relic-yuexi I do not see a PR for this yet. Were you going to make one? If not, I can give it a go, as I have a specific use case I can test it for directly.

https://github.com/vanna-ai/vanna/pull/160/commits/8047a38548014e18bd8418078477e85942ac26fc

There. you can use this code to load the embedding model as you download.
```python
from chromadb.utils import embedding_functions

bge_embeddingFunction = embedding_functions.SentenceTransformerEmbeddingFunction("/AI-ModelScope/bge-large-zh-v1.5","cuda",normalize_embeddings=True)

```

then use the config to chromadbvector
```python
config = {"embedding_function":bge_embeddingFunction, "path": "/root/chatdb/chromadb"}
vs = ChromaDB_VectorStore(config)
```

then it will all use the bge_embedding or you have downloaded

**Comment by andreped** [comment]
> 8047a38

@relic-yuexi Sorry, I misunderstood your first reply. I can run a test to see if this addresses issue (2), which is the most critical one to fix. Cheers! :]

**Comment by roshanr10** [comment]
is there an expected configuration pattern for `Allowing to use in-memory vector database with ChromaDB, hence not saving anything on disk`?

I'd love to use an in-memory version as I intend to primarily load DDL from the database anyway and would reload from scratch every time

**Comment by relic-yuexi** [comment]
> is there an expected configuration pattern for `Allowing to use in-memory vector database with ChromaDB, hence not saving anything on disk`?
> 
> I'd love to use an in-memory version as I intend to primarily load DDL from the database anyway and would reload from scratch every time

maybe you can use faiss , it is just a vector search tool as you want in memory

https://github.com/facebookresearch/faiss

**Comment by andreped** [comment]
> I'd love to use an in-memory version

@roshanr10 ChromaDB supports in-memory storage but the Chroma instance setup by Vanna does not. There is no API in Vanna to use in-memory instead of persistent store for Chroma:
https://github.com/vanna-ai/vanna/blob/b3d46dc5c64d48bd7b8255ba557d1b12ec651903/src/vanna/chromadb/chromadb_vector.py#L27C30-L27C55

I can make a PR now to address this as I need this myself.

**Comment by andreped** [comment]
@roshanr10 I have now made a PR to add in-memory support. PR: https://github.com/vanna-ai/vanna/pull/250

**Comment by andreped** [comment]
Merged in https://github.com/vanna-ai/vanna/pull/250.

Will be part of next sprint.
