### ISSUE TITLE
Is it possible to use HttpClient with Chroma in Vanna?

### ISSUE THREAD

**Issue by andreped** [vanna-ai/vanna#249]
**Is your feature request related to a problem? Please describe.**
As seen in the documentations of Chroma, `PersistentClient`, which is the only storage solution Vanna's Chroma instance supports, is not recommended for production use (see [here](https://docs.trychroma.com/reference/Client#persistentclient)). In-memory store called `EphemeralClient` has the same problem.

The documentations recommend using an `HttpClient` instead (see [here](https://docs.trychroma.com/reference/Client#httpclient)). That way the Chroma instance is remote and communication is performed through an endpoint. This also allows for multiple clients accessing the same server.

**Describe the solution you'd like**
Vanna should allow all three Chroma clients through setting the client type in the `config` which then is used to construct the Chroma instance inside Vanna.

If there are any other ways to change the Chroma Client, which still allow me to use Vanna, I am very interested to know how :]

---
EDIT: I am open to making a PR to address this.

**Comment by zainhoda** [comment]
Thanks @andreped ! If you'd like to make a PR for this, that would be amazing!

**Comment by zainhoda** [comment]
Two PRs is totally fine with me! Thanks!

**Comment by andreped** [comment]
Do you have any suggestion on how we can best add support for `HttpClient`? See [here](https://docs.trychroma.com/reference/Client#httpclient) for how it works in Chroma.

From the link above, the two fundamental difference are that for PersistentClient we do:
```
def PersistentClient(path: str = "./chroma",
                     settings: Settings = Settings()) -> API
```

While for `HttpClient` we do:
```
def HttpClient(
    host: str = "localhost",
    port: str = "8000",
    ssl: bool = False,
    headers: Dict[str, str] = {},
    settings: Settings = Settings()) -> API
```

**Comment by andreped** [comment]
Hmm, how am I to run tests if I do not have these following three keys?
https://github.com/vanna-ai/vanna/blob/main/tests/test_vanna.py#L18

Would it be possible to do this solely using the Vanna e-mail I created? Hence, I am at least able to get the Vanna key. But more tricky with OpenAI and Mistral. Any thoughts?

**Comment by zainhoda** [comment]
I’ve been researching this and unfortunately it doesn’t seem like there’s
an easy way to run the tests using repository secrets when you’re not a
member of the repository. It’s a GitHub security mechanism.

I’ve thought about putting some mocks in so that we have a subset of tests
that are run against a mock implementation that doesn’t need any API keys.
I’m not totally sure if that would be particularly useful though since most
of what Vanna does is serve as a connector for various components.

For now, don’t worry about the tests. I’ve set the tests to run on merge
into main and I’m going to follow a procedure of accepting PRs into main
but then make sure that the tests pass before creating a release.

**Comment by andreped** [comment]
> For now, don’t worry about the tests.

OK, great! But then the PR is ready to review. If you see something immediately off, let me know :] I can do the linting when I get home on my other laptop, if necessary.

**Comment by andreped** [comment]
Merged in https://github.com/vanna-ai/vanna/pull/250.

Will be part of upcoming release.

**Comment by lkiii** [comment]
Hi, i am trying to utilize this and I am getting quite random issue.

My initiation is:

```python
class MyVanna(ChromaDB_VectorStore, OpenAI_Chat):
    def __init__(self, config=None):
        ChromaDB_VectorStore.__init__(self, config=config)
        OpenAI_Chat.__init__(self, config=config)

config = {
    "api_key": api_key,
    "model": model,
    "client": chromadb.HttpClient(
        host=chromadb_host,
    ),
}

vn = MyVanna(config=config)


```
This fails with `TypeError: Collection.__init__() got an unexpected keyword argument 'log_position'`

I was debugging all the flow and `log_position` is being returned from the ChromaDB call

Example:
```json
{"id":"b4b35fd3-57e5-46fd-bd22-6c1d1d2b96de","name":"documentation","configuration_json":{"hnsw_configuration":{"space":"l2","ef_construction":100,"ef_search":10,"num_threads":2,"M":16,"resize_factor":1.2,"batch_size":100,"sync_threshold":1000,"_type":"HNSWConfigurationInternal"},"_type":"CollectionConfigurationInternal"},"metadata":null,"dimension":null,"tenant":"default_tenant","database":"default_database","version":0,"log_position":0}
```

**Comment by andreped** [comment]
> Hi, i am trying to utilize this and I am getting quite random issue.

@lkiii Can you open a separate issue on this, and we can open a PR if we manage to reproduce and implement a fix.

Feel free to link the issue to this one, if you think that is relevant :]
