### ISSUE TITLE
openai.APITimeoutError: Request timed out

### ISSUE THREAD

**Issue by njalan** [vanna-ai/vanna#252]
I am trying to use openai and chromadb to generate sql but got **openai.APITimeoutError: Request timed out**
Below is my code:

from vanna.openai.openai_chat import OpenAI_Chat
from vanna.chromadb.chromadb_vector import ChromaDB_VectorStore

class MyVanna(ChromaDB_VectorStore, OpenAI_Chat):
        def __init__(self, config=None):
            ChromaDB_VectorStore.__init__(self, config=config)
            OpenAI_Chat.__init__(self, config=config)

vn = MyVanna(config={'api_key': 'xxxxx', 'model': 'text-davinci-003','base_url':'http://xxxxx:8000/v1'})

import mysql.connector

vn.train(ddl="""
    create table xxxx
(
   xxxx
);

""")

vn.ask(question="how many ids ")

Below is the output:
Using model text-davinci-003 for 1368.25 tokens (approx)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
**Request timed out.
(None, None, None)**

**Comment by andreped** [comment]
@njalan It would be great if you could report what the issue/fix was, as someone might run into the same issue down the line :]
