### ISSUE TITLE
No module named 'vanna.flask'

### ISSUE THREAD

**Issue by njhouse365** [vanna-ai/vanna#293]

**Comment by andreped** [comment]
Hello, @njhouse365! 

Can you add a description on how to reproduce the bug?

**Comment by andreped** [comment]
At least this runs fine:
```
pip install git+https://github.com/vanna-ai/vanna.git
python -c "from vanna import flask"
```

But maybe there is a bug somewhere in the code for something you are trying to do?

**Comment by njhouse365** [comment]
oh,thanks

**Comment by njhouse365** [comment]
python -c "from vanna import flask"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'flask' from 'vanna' (/home/xxm/anaconda3/envs/vanna/lib/python3.10/site-packages/vanna/__init__.py)


python -c "import vanna.flask"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'vanna.flask'

**Comment by zainhoda** [comment]
@njhouse365 are you using an old version of Vanna -- can you try `pip install -U vanna` ?

**Comment by njhouse365** [comment]
it works !!!,thanks
