### ISSUE TITLE
Why is the data in the order date row of the data table incorrect?

### ISSUE THREAD

**Issue by jeffreyrobeson** [vanna-ai/vanna#307]
**Describe the bug**
Why is the data in the order date row of the data table incorrect? The Plotly chart is correct. How can I correct this error?

![872790ac236e0b44f83471775bbb903e](https://github.com/vanna-ai/vanna/assets/132809848/8f55f795-643e-4b8a-8a25-08fc826dd8aa)

![81b320e7a9090c68791823b18a589e12](https://github.com/vanna-ai/vanna/assets/132809848/b827f41b-4a2a-42b3-b109-164011519a53)

**Desktop (please complete the following information where):**
 - OS: windows 10
 - Version: 
 - Python: 3.10
 - Vanna: 0.2.1

**Additional context**
SELECT 
    下单日期,
    SUM(已分账收益) AS 已分账收益总额,
    SUM(未分账收益) AS 未分账收益总额,
    SUM(已分账收益 + 未分账收益) AS 总收益
FROM 
    orders
GROUP BY 
    下单日期;

**Comment by jeffreyrobeson** [comment]
#upgrade vanna-0.3.0
pip install --upgrade vanna
The problem has been solved.

**Comment by jeffreyrobeson** [comment]
The problem has been solved.

**Comment by zainhoda** [comment]
@jeffreyrobeson thanks! In this particular case it looks like the generated SQL query does not contain an order by so the results in the table wouldn't be expected to be sorted. Plotly might be sorting the dates automatically under the hood.

**Comment by jeffreyrobeson** [comment]
Thanks!

**Comment by jeffreyrobeson** [comment]
thx.
