### ISSUE TITLE
SQL datetime format returns as integer value in Vanna flask app

### ISSUE THREAD

**Issue by akhilvk** [vanna-ai/vanna#312]
while returning query results , Vanna App converts datetime fields into UNIX time format. how can i return the results in readable formats like "dd-MM-yyyy HH:mm:ss". i have tried adding in documentation like 

`vn.train(documentation="Use dd-MM-yyyy HH:mm:ss format for sql field with type datetime2(0)")`

but couldnt find any changes. see attached image

![image](https://github.com/vanna-ai/vanna/assets/16642260/bcede34c-70cf-4ac9-b5e7-b724492031fa)

**Comment by zainhoda** [comment]
This will be fixed in the next release. It is purely a display issue in the flask app.

**Comment by zainhoda** [comment]
Fix in `v0.3.x`
