### ISSUE TITLE
"logo" option not working as expected in built-in-app - v0.3.0

### ISSUE THREAD

**Issue by assinchu** [vanna-ai/vanna#324]
**Describe the bug**

logo option in vanna init not working as expected

__init__(vn, 
cache=MemoryCache(), 
allow_llm_to_see_data=False, 
logo="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg",
......
)

**To Reproduce**
app = VannaFlaskApp(vn,
        allow_llm_to_see_data=True,
        logo="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg",
        title="Welcome to ",
        subtitle="Your  copilot for SQL queries.",
        show_training_data=False,
        suggested_questions=True,
        sql=True,
        table=True,
        csv_download=True,
        chart=True,
        redraw_chart=False,
        auto_fix_sql=True,
        ask_results_correct=False,
        followup_questions=False,
        summarization=True)
app.run()

**Expected behavior**
Vanna logo should be replaced with given logo

 - OS: [Ubuntu]
 - Version: [22.04]
 - Python: [3.10]
 - Vanna: [v0.3.0]

**Comment by zainhoda** [comment]
Thank you for reporting this. It should be fixed now in `v0.3.2`
