### ISSUE TITLE
Training data is not updated properly

### ISSUE THREAD

**Issue by njalan** [vanna-ai/vanna#328]
When I set the answer is wrong and put the right query to run. But the training data is  still with the wrong query for that question.

 - OS: Centos
 - Version: 7.9
 - Python: 3.9
 - Vanna: 0.3.1

**Additional context**

**Comment by Simon-Ceng** [comment]
I found the same problem too. Now I have to update train data by code instead of website.

**Comment by njalan** [comment]
@zainhoda Can you please take a look at this issue?

**Comment by zainhoda** [comment]
This will be fixed in the next release

**Comment by njalan** [comment]
@zainhoda May I know when is the e next release

**Comment by zainhoda** [comment]
This is fixed in the latest version
