### ISSUE TITLE
Why is settings for `n_results` not supported for `get_related_documentation` and `get_related_ddl`? 

### ISSUE THREAD

**Issue by imzdu** [vanna-ai/vanna#357]
Hi Team,

Would like to understand why the argument `n_results` is supported for `get_similar_question_sql`:
https://github.com/vanna-ai/vanna/blob/fe2d4396c2ca946790895b441dbefa65c5af890f/src/vanna/chromadb/chromadb_vector.py#L233C9-L233C33

But not for `get_related_documentation` or `get_related_ddl`? See reference below:

https://github.com/vanna-ai/vanna/blob/fe2d4396c2ca946790895b441dbefa65c5af890f/src/vanna/chromadb/chromadb_vector.py#L243C13-L243C39

Would like the ability to set how many documents or ddl statements to consider for in-context learning.

**Comment by andreped** [comment]
@imzdu Just so that you are aware. There has been implemented a PR to address this: https://github.com/vanna-ai/vanna/pull/354

Hopefully it will be merged and a new release will be made very soon. Any update on when the release will be made, @zainhoda? :]

**Comment by zainhoda** [comment]
Oh @andreped I thought you were going to test that change on your end. If you’re good with it, I’ll release that as a minor patch
