### ISSUE TITLE
【feat】Could OpenSearch vector database to be supportted?

### ISSUE THREAD

**Issue by zyclove** [vanna-ai/vanna#388]
https://github.com/opensearch-project/OpenSearch

The OpenSearch vector database is very good in use and performance, and its maturity is also high. I hope it can be scheduled to be supported. 

Best regards.

**Comment by zainhoda** [comment]
Feel free to submit a PR!

**Comment by zyclove** [comment]
https://github.com/vanna-ai/vanna/issues/388 @zainhoda

**Comment by zainhoda** [comment]
Awesome! I'll review and merge this week
