### ISSUE TITLE
More informative results after running vn.train()

### ISSUE THREAD

**Issue by westerleyy** [vanna-ai/vanna#40]
Running `vn.train()` returns `True` regardless of whether the SQL that is trained is correct or not. It also does not show whether the question that is being trained already exists. If it does, then what does `vn.train()` do? This raises the following issues:

1. Returning `True` is not informative. It gives the impression that the SQL trained is correct but it might not be. I was able to train on erroneous SQL queries and it returned `True` as well.
2. In what scenarios will `False` be returned?
3. Are existing questions and their SQL code overwritten when `vn.train()` is run with an existing question?

**Comment by zainhoda** [comment]
We should stop returning True/False: #47 
Running SQL: #19 
We do need to ensure that training data isn't duplicated
