### ISSUE TITLE
Error caused when using llama:70b (currently solved by modifying the vanna/ollama/ollama.py file, we hope to fix this problem in subsequent versions)

### ISSUE THREAD

**Issue by Mioooooo** [vanna-ai/vanna#404]
![image](https://github.com/vanna-ai/vanna/assets/37464936/ee6803f0-add5-4170-95d2-97f862272050)

In line 27, if my model is llama:70b, it will be modified to llama:70b:latest

**Comment by Mioooooo** [comment]
Currently I modified the code to [in -> not in] and it ran successfully

**Comment by zainhoda** [comment]
Thanks @Mioooooo — would you like to submit a PR?

**Comment by zainhoda** [comment]
@Mioooooo did v0.5.3 address this issue for you?

**Comment by Mioooooo** [comment]
> @Mioooooo did v0.5.3 address this issue for you?

Yes, I saw and updated the latest version. This problem has been successfully solved. Thank you.

**Comment by zainhoda** [comment]
Thanks for confirming!
