### ISSUE TITLE
System prompt does not consider inputs from add_sql_to_prompt

### ISSUE THREAD

**Issue by sourabh-patil** [vanna-ai/vanna#413]
**Describe the bug**
In get_sql_prompt definition of VannaBase class, current code does not include similar Question-SQL pairs from db in system message

**Expected behavior**
Current code considers inputs only from DDL (add_ddl_to_prompt) and documentation (add_documentation_to_prompt) collections from db. As per the Ask phase, we should consider reference SQL too. 

**Error logs/Screenshots**
[https://github.com/vanna-ai/vanna/blob/7b962d59c7ad7a0e976f179473ab9f18d1e0581b/src/vanna/base/base.py#L557-L591](url)

**Additional context**
Correct me if I am wrong, also will try to PR if we need to add in reference SQL.

**Comment by zainhoda** [comment]
They're not added as part of the system prompt. They're instead added as user / assistant messages:

https://github.com/vanna-ai/vanna/blob/main/src/vanna/base/base.py#L583-L589
