### ISSUE TITLE
Plotly chart arising from `vn.ask()`

### ISSUE THREAD

**Issue by westerleyy** [vanna-ai/vanna#42]
The chart generated by `vn.ask()` cannot be replotted if it is not to the user's liking. But they should be able to. Otherwise, users might have to reshape the resultant df, and do the plotting themselves. The value presented by Vanna might be diminished somewhat in this instance

**Comment by zainhoda** [comment]
What would your ideal behavior look like?

**Comment by westerleyy** [comment]
I can think of two workflows. The first will be:
1. vn.ask('Question')
2. query, df, plot, followup qns printed
3. text-box asking whether the plot is what the user wants
4. attempts to replot 

The second will be:
1. vn.ask('Question', '[Optional] Plotting instructions')
2. query, df, plot, followup qns printed
3. If it is not what the user wants, they can run vn.ask() again but with more detailed/different plotting instructions

If the user is going to be a data analyst who can rewrite SQL queries and integrate Vanna into a broader python workflow, they are also likely to have some idea of what are the graphs/chart that they want
