### ISSUE TITLE
Vanna with qdrant using old endpoints from qdrant v.1.0.0 or before

### ISSUE THREAD

**Issue by mohamedamine456** [vanna-ai/vanna#444]
**Describe the bug**
I am using vanna.ai with a qdrant vector db running in a docker container, and when you try to verify if collection exists using "GET /collections/sql/exists" I get this error in the qdrant container logs "GET /collections/sql/exists HTTP/1.1" 404 which means, the endpoint does not exist, and I think bcs you are based on an old version of qdrant 1.0.0 or before, but the new version uses GET "/collections/{collection_name}"
this 

**To Reproduce**
1. use vanna.ai with newest version of qdrant database
2. try the example code given in the docs to use vanna with qdrant database

**Expected behavior**
to access qdrant database and find/create the needed collection

**Error logs/Screenshots**
If applicable, add logs/screenshots to give more information about the issue.

**Desktop (please complete the following information where):**
 - OS: [e.g. docker]
 - Version: [e.g. 20.04]
 - Python: [3.9]
 - Vanna: [2.8.0]

**Additional context**
also the endpoints used to create new collection changed

**Comment by zainhoda** [comment]
@Anush008 could you kindly confirm?

**Comment by mohamedamine456** [comment]
I was using the version 1.6.1 of qdrant, I ll update it to latest, thank you
