### ISSUE TITLE
Excessive print outs from `vn.ask()`

### ISSUE THREAD

**Issue by westerleyy** [vanna-ai/vanna#46]
![image](https://github.com/vanna-ai/vanna-py/assets/47231787/9b77f29c-e008-4d35-a878-a2363fea1baf)
Can we omit the print outs that come after the chart in `vn.ask()`? Unnecessary, repetitive, and result in a lot of scrolling

**Comment by zainhoda** [comment]
If you do `sql, df, fig, followup_questions = vn.ask(...)`, you won't get this extra output
