### ISSUE TITLE
NoneType object has no attribute questions

### ISSUE THREAD

**Issue by Rainismer** [vanna-ai/vanna#462]
from vanna.remote import VannaDefault
from google.colab import userdata
vn = VannaDefault(model='gpt-4o', api_key=userdata.get('OPENAI_API_KEY'))
vn.connect_to_sqlite('https://vanna.ai/Chinook.sqlite')
vn.ask("What are the top 10 albums by sales?")
-----------------------------------------------------------------------------------------------
'NoneType' object has no attribute 'questions'

**Comment by anechii** [comment]
following this, I have the same problem

**Comment by anechii** [comment]
@Rainismer  [issue 465](https://github.com/vanna-ai/vanna/issues/465)

**Comment by Rainismer** [comment]
@anechii I got it. My model and aip key are incorrect.
