### ISSUE TITLE
Cannot set the collection name for ddl, sql, and documentation from Qdrant.

### ISSUE THREAD

**Issue by doanhieu9797** [vanna-ai/vanna#464]
When setup vanna with qdrant i have error with name collection here my setup vanna with qdrant:
`vn = MyVanna(config={
        'client': QdrantClient(url='http://localhost:6333', timeout=300),
        'api_key': openai_api_key,
        'model': model,
        'documentation_collection_name':f'documentation_{table_name}', 
        'ddl_collection_name':f'ddl_{table_name}',
        'sql_collection_name':f'sql_{table_name}',
        'fastembed_model':f'sentence-transformers/all-MiniLM-L6-v2'
    })`

After checking your code snippet that connects to Qdrant, I noticed that after sql_collection_name, documentation_collection_name, and ddl_collection_name were reset, the id_suffixes was not updated, which caused the key_error: ddl_{custom collection name}. Please update the source code with the patch. Thank you.

<img width="436" alt="image" src="https://github.com/vanna-ai/vanna/assets/43605993/751c019c-dc17-406e-af77-38be647694ce">

**Comment by ShreyasVaishnav** [comment]
> When setup vanna with qdrant i have error with name collection here my setup vanna with qdrant: `vn = MyVanna(config={ 'client': QdrantClient(url='http://localhost:6333', timeout=300), 'api_key': openai_api_key, 'model': model, 'documentation_collection_name':f'documentation_{table_name}', 'ddl_collection_name':f'ddl_{table_name}', 'sql_collection_name':f'sql_{table_name}', 'fastembed_model':f'sentence-transformers/all-MiniLM-L6-v2' })`
> 
> After checking your code snippet that connects to Qdrant, I noticed that after sql_collection_name, documentation_collection_name, and ddl_collection_name were reset, the id_suffixes was not updated, which caused the key_error: ddl_{custom collection name}. Please update the source code with the patch. Thank you.
> 
> <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/43605993/334733442-751c019c-dc17-406e-af77-38be647694ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzk3NDEsIm5iZiI6MTcxNzMzOTQ0MSwicGF0aCI6Ii80MzYwNTk5My8zMzQ3MzM0NDItNzUxYzAxOWMtZGMxNy00MDZlLWFmNzctMzhiZTY0NzY5NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE0NDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzBkYzY5NGY2YTcyOGNkNWQ4NTMwNTI3NjBjNTViMzdhNmE4ZDYyNWEzMjcxOTlkMTVhYmNkZTVhY2U5NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qfQO7Xc8kYCJ6l4XnJBP39Ur4wOztYrLL4TaT9LkS_Y">

Yes. I have noticed the same issue. This needs to be patched.
