### ISSUE TITLE
Does it works? Or is it just yet another mess?

### ISSUE THREAD

**Issue by antonio-gabriele** [vanna-ai/vanna#468]
pip install openai
pip install vanna[openai,chromadb]

>>> vanna.py
from openai import AzureOpenAI
from vanna.openai import OpenAI_Chat
from vanna.chromadb import ChromaDB_VectorStore
>>>

python vanna.py

Traceback (most recent call last):
  File "C:\Work\vanna\vanna.py", line 2, in <module>
    from vanna.openai import OpenAI_Chat
  File "C:\Work\vanna\vanna.py", line 2, in <module>
    from vanna.openai import OpenAI_Chat
ModuleNotFoundError: No module named 'vanna.openai'; 'vanna' is not a package

**Comment by deathblade287** [comment]
This is not a bug. The name of both the module (this library) and your file is `vanna.py` - python sometimes gets confused by this. Try renaming your file to `main.py` or really anything else and let me know if the error persists.

**Comment by zainhoda** [comment]
@deathblade287 is correct. @antonio-gabriele please rename your file.
