### ISSUE TITLE
Vanna.ai not supporting multi-line strings in training data

### ISSUE THREAD

**Issue by MelzCoss** [vanna-ai/vanna#500]
It seems that Vanna is no longer supporting multi-line strings is training data, like:

`vn.train(documentation="""
Some informations..
""")`

In facts this type of documentation is not added in the prompt. Any suggestions?

**Comment by Marck100** [comment]
Same problem

**Comment by zainhoda** [comment]
I don't see this issue. What setup are you using?

![Screenshot 2024-06-18 at 8 25 14 AM](https://github.com/vanna-ai/vanna/assets/7146154/c312713c-dec6-4a57-8ad8-998207007c8e)

**Comment by MelzCoss** [comment]
> I don't see this issue. What setup are you using?
> 
> ![Screenshot 2024-06-18 at 8 25 14 AM](https://private-user-images.githubusercontent.com/7146154/340672856-c312713c-dec6-4a57-8ad8-998207007c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODI5NDAsIm5iZiI6MTcxODc4MjY0MCwicGF0aCI6Ii83MTQ2MTU0LzM0MDY3Mjg1Ni1jMzEyNzEzYy1kZWM2LTRhNTctOGFkOC05OTgyMDcwMDdjOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMDczNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdiNDA3ZjU5NDkyM2ViNmNlYmUxYTZkNDE2NDAxODMyZmFiNzgxZjUwYTgyMzA5NzcyM2JkYjk1ZTdlYjdmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ymErnI-9Ih5cxWBl4CF95Lv1DufbzhARlpvM6sGLDks)

I apologize for not explaining myself well. The DDL documentation is inserted in the training data, however when generating the query I see that the prompt is missing the DDL part after "===Tables", consequently the generated queries cannot be based on a schema. The problem started from version 0.5.5 of Vanna, I solved it by installing 0.5.4.
