### ISSUE TITLE
AttributeError: 'MyVanna' object has no attribute 'client'

### ISSUE THREAD

**Issue by Rainismer** [vanna-ai/vanna#571]
from vanna.openai import OpenAI_Chat
from vanna.vannadb import VannaDB_VectorStore

class MyVanna(VannaDB_VectorStore, OpenAI_Chat):
    def __int__(self, vanna_model, vanna_api_key, config=None):
        VannaDB_VectorStore.__init__(self, vanna_model=vanna_model, vanna_api_key=vanna_api_key, config=config)
        OpenAI_Chat.__init__(self, config=config)

VANNA_MODEL = "xxx"
VANNA_API_KEY = "xxx"
vn = MyVanna(VANNA_MODEL, VANNA_API_KEY, config={"api_key": "xxx", "model": "gpt-4o"})
vn.connect_to_postgres(host='xxx', dbname='xxx', user='xxx', password='xxx', port='xxx')
vn.train(question="找出发票金额最多的前3个开票申请单号", sql="select max(invoice_money) invoice_money from iss_edm.edm_fi_wipeout_items_invoice_bill limit 3;")
vn.ask("找出发票金额最多的前3个开票申请单号")

**Comment by IwGrin** [comment]
in the quickstart use openai,vannaDB,mysql:  'MyVanna' object has no attribute 'client'

**Comment by dusens** [comment]
try replace VannaDB_VectorStore to ChromaDB_VectorStore
