### ISSUE TITLE
Impossibility to use Mistral AI as LLM 

### ISSUE THREAD

**Issue by BaptisteLeDuc-eaton** [vanna-ai/vanna#591]
**Describe the bug**
Error : `ModuleNotFoundError: No module named 'mistralai.models.chat_completion'` when trying to import Mistral from vanna.mistral

**To Reproduce**
Simply Run :  `from vanna.mistral import Mistral` as described in doc [https://vanna.ai/docs/mysql-mistral-chromadb/](url)

**Expected behavior**
Module `chat_completion` should be found in `mistralai.models`

**Error logs/Screenshots**

![Screenshot 2024-08-08 133018](https://github.com/user-attachments/assets/94cc0f4c-28ba-4666-aa40-acda75b1db9a)

**Desktop (please complete the following information where):**
 - OS: [WSL Ubuntu]
 - Version: [e.g. 22.04.4 LTS]
 - Python: [3.12.4]
 - Vanna: [2.8.0]
 - mistralai: [1.0.0]

**Comment by zainhoda** [comment]
It looks like we need to migrate our mistral implementation after they released their 1.0.0 version:

https://github.com/mistralai/client-python/blob/55b92b18b36ed909e5b56036d6c7962f66447067/MIGRATION.md
