### ISSUE TITLE
If the app starts without training data, there’s an error shown, also there is no option to add training data.

### ISSUE THREAD

**Issue by sqlquery** [vanna-ai/vanna#611]
UI is not showing option to add training data while vanna flask app. why is it so?

**Comment by sqlquery** [comment]
![Screenshot 2024-08-22 153006](https://github.com/user-attachments/assets/2e05e1b8-d7d4-4260-bfcd-4b0e2fd73a13)

**Comment by zainhoda** [comment]
This is intentional behavior. See #613
