### ISSUE TITLE
No option to increase fetch limit for Weviate Vector DB

### ISSUE THREAD

**Issue by talrejanikhil** [vanna-ai/vanna#615]
**Is your feature request related to a problem? Please describe.**
As of now, the no. of results that can be fetched for Weviate DB is hard coded to 3. This should be flexible like it is for other vector stores

**Describe the solution you'd like**
The no. of results fetched for Weviate DB should be changeable using config.
Here is an example for ChromaDB
```
self.n_results_sql = config.get("n_results_sql", config.get("n_results", 10))
self.n_results_documentation = config.get("n_results_documentation", config.get("n_results", 10))
self.n_results_ddl = config.get("n_results_ddl", config.get("n_results", 10))
```
And pinecone
```
self.n_results = config.get("n_results", 10)
```

**Describe alternatives you've considered**
Using a different vector store

**Comment by zainhoda** [comment]
I agree with this. Ideally these should be configurations in the base class that is implemented for every vector store.

**Comment by talrejanikhil** [comment]
Could I do a quick fix for Weviate for now? I am not sure what is the plan for having it across all vector stores

**Comment by zainhoda** [comment]
@talrejanikhil you have a couple of options -- if you want to submit a PR you're more than welcome to do so. The other alternative is to follow the setup for "Other Vector Database" and then just copy/paste the implementation from Weaviate and then make the necessary modifications.

**Comment by talrejanikhil** [comment]
I am unable to push changes to my branch. Can you please grant access?

**Comment by zainhoda** [comment]
You have to first fork and then submit a PR from the fork

**Comment by talrejanikhil** [comment]
https://github.com/vanna-ai/vanna/pull/616
