### ISSUE TITLE
openai.APIConnectionError with AzureOpenAI

### ISSUE THREAD

**Issue by alouiadel** [vanna-ai/vanna#620]
Summary:

I’m running into an openai.APIConnectionError in my FastAPI app when trying to use Azure OpenAI. Even though I’ve set up AZURE_ENDPOINT, AZURE_API_VERSION, and AZURE_API_KEY, the app can’t seem to connect to the Azure OpenAI API. The error trace shows that everything seems to be configured correctly, but the connection just isn't going through.

**Comment by HamburgerTwo** [comment]
I have this problem too

**Comment by alouiadel** [comment]
@zainhoda can we get some help ? thank you

**Comment by zainhoda** [comment]
Are you able to connect any OpenAI client to Azure without Vanna? If you’re able to successfully connect that client, then you should just be able to pass that client into the Vanna object

**Comment by HamburgerTwo** [comment]
I sloved with correct the azureopenai paramter api_version.maybe you find the api_version from 
![image](https://github.com/user-attachments/assets/8daa7695-4df7-4c62-9f67-12e992893791)
,but it's wrong,so i get the right version last,so it's just a mistake by using wrong paramster

**Comment by alouiadel** [comment]
> Are you able to connect any OpenAI client to Azure without Vanna? If you’re able to successfully connect that client, then you should just be able to pass that client into the Vanna object

yes i am using AzureOpenAI elsewhere , passing same object to vanna.ai returned : 
`AttributeError: 'function' object has no attribute 'completions'`

**Comment by zainhoda** [comment]
@alouiadel what versions do you have of openai and vanna?

`pip show vanna`

`pip show openai`

**Comment by alouiadel** [comment]
thanks for the reply , but i am closing this as i stopped working on the project
