### ISSUE TITLE
PG Vector not working

### ISSUE THREAD

**Issue by edlouth** [vanna-ai/vanna#659]
**Describe the bug**
I have setup pg_vector like so:

```
from vanna.pgvector import PG_VectorStore
from vanna.openai import OpenAI_Chat

class CustomVanna(PG_VectorStore, OpenAI_Chat):
    def __init__(self, config=None):
        PG_VectorStore.__init__(self, config=config)
        OpenAI_Chat.__init__(self, config=config)

vn = CustomVanna(config={
    "api_key": openai_api_key,
    "connection_string": connection_string
})

# The information schema query may need some tweaking depending on your database. This is a good starting point.
df_information_schema = vn.run_sql("SELECT * FROM `...demo.INFORMATION_SCHEMA.COLUMNS`;")

# This will break up the information schema into bite-sized chunks that can be referenced by the LLM
plan = vn.get_training_plan_generic(df_information_schema)

vn.train(plan=plan)
```

I get the following error:

`AttributeError: 'CustomVanna' object has no attribute 'documentation_collection'`

If I run:

```
vn.ask(question="How many users are there?")
```

I get an error of `object of type 'coroutine' has no len()`

**Comment by edlouth** [comment]
@andreped I thought I'd mention you as it looks like you are the author of these changes.

**Comment by andreped** [comment]
Hello, @edlouth :] Thank you for reporting the bug!

I was surprised the PR I made was merged so quickly. I don't think we did thorough testing on it, especially not integration tests.
We should aim to fix this before the new release is out.

I can draft a PR on this today :]

**Comment by edlouth** [comment]
@andreped thanks for getting back so soon.

I have opened a PR https://github.com/vanna-ai/vanna/pull/660 which I think has the changes in question.

**Comment by edlouth** [comment]
While we are here I have also had some issues with

https://github.com/vanna-ai/vanna/blob/c21d8bf8c086a9c52ab6178f03cf4eee41051b08/src/vanna/pgvector/pgvector.py#L32

I think this works

```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

# Define a custom embedding class with the necessary methods
class CustomEmbeddingFunction:
        def __init__(self, model):
                self.model = model

        def embed_documents(self, texts):
                # Return embeddings for documents
                return self.model.encode(texts, convert_to_tensor=False)

        def embed_query(self, text):
                # Return embedding for a query
                return self.model.encode([text], convert_to_tensor=False)[0]
            
        self.embedding_function = CustomEmbeddingFunction(model)
```

**Comment by andreped** [comment]
> Hi @edlouth, could you please guide me on how to utilize vanna.pgvector? I attempted to install Vanna with pgvector using `pip install 'vanna[pgvector]'` but encountered an issue where Vanna 0.7.3 does not offer the extra 'pgvector'. I intended to utilize my local database (pgvector) for vector storage.

Hello, @VirendraSttl :]

There has yet to be made a release including the new `pgvector` support, so you can't use it like this.

A way to install the latest, could be to do something like this below:
```
pip install git+https://github.com/vanna-ai/vanna.git#egg=vanna[pgvector]
```

Then again, as this seems broken right now, and has been addressed in the PR by @edlouth, but has yet to be merged, I would install Vanna through the following to get proper pgvector support:
```
pip install git+https://github.com/edlouth/vanna.git@pgvector_fixes#egg=vanna[pgvector]
```

At least something like that should work.

**Comment by isaacdalmarco** [comment]
Hi @andreped, I am trying to use pgvector as a custom vector database and I have copied the pgvector to my project. 
But when it starts i get this error:

../.pyenv/versions/3.12.6/lib/python3.12/site-packages/langchain_postgres/vectorstores.py", line 106, in _get_embedding_collection_store
    from pgvector.sqlalchemy import Vector  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pgvector.sqlalchemy'; 'pgvector' is not a package

I tried to run in python 3.12 and 3.11, changed pgvector and langchain_postgres versions, but none worked.

Which version of python are you using? Do you have any other suggestion?

**Comment by andreped** [comment]
I think we should wait till PR https://github.com/vanna-ai/vanna/pull/660 is merged.

Then we can try to see how to fix this issue of yours.

**Comment by andreped** [comment]
@edlouth, @isaacdalmarco A new release of `vanna==0.7.4` was just released (see [here](https://pypi.org/project/vanna/0.7.4/)), which should have resolved the original issue and maybe the one @isaacdalmarco is having.

Could you try to upgrade to the latest version and test if this new version works well with you? :]

**Comment by fernando0da0costa** [comment]
`import json
import pandas as pd
import psycopg2
import os
from langchain_openai import OpenAIEmbeddings
from vanna.base import VannaBase
from vanna.openai import OpenAI_Chat
import uuid
import hashlib

os.environ["NLS_LANG"] = "AMERICAN_AMERICA.AL32UTF8"

def deterministic_uuid(data: str) -> str:
    """Generate a deterministic UUID based on input data."""
    return str(uuid.UUID(hashlib.md5(data.encode('utf-8')).hexdigest()))

class PGvectorCustomVectorDB(VannaBase):
    def __init__(self, config=None, name_vector='vanna_ia'):
        try:
            self.conn = psycopg2.connect(
                dbname=os.environ.get('DB_NAME'),
                user=os.environ.get('DB_USER'),
                password=os.environ.get('DB_PASSWORD'),
                host=os.environ.get('DB_HOST')
            )
            self.name_vector = name_vector.strip().lower().replace('-', '_')
            self.cursor = self.conn.cursor()
            self.n_results_sql = config.get("n_results_sql", config.get("n_results", 10)) if config else 10
            self.n_results_ddl = config.get("n_results_ddl", config.get("n_results", 10)) if config else 10
            self.n_results_documentation = config.get("n_results_documentation", config.get("n_results", 10)) if config else 10
            self._ensure_tables_exist()
            self._create_indexes()
            self.embed = lambda text: self.get_embedding(text)
        except psycopg2.Error as e:
            raise Exception(f"Failed to connect to database: {e}")

    def to_pgvector_str(self, embedding: list[float]) -> str:
        return "[" + ",".join(f"{x:.6f}" for x in embedding) + "]"

    def generate_embedding(self, text: str) -> list:
        try:
            embedder = OpenAIEmbeddings(api_key=os.environ.get('OPENAI_API_KEY'))
            return embedder.embed_query(text)
        except Exception as e:
            raise Exception(f"Failed to generate embedding: {e}")

    def get_embedding(self, text: str) -> list:
        try:
            return self.generate_embedding(text)
        except Exception as e:
            raise Exception(f"Failed to generate embedding: {e}")

    def add_ddl(self, ddl: str, **kwargs) -> str:
        try:
            id = deterministic_uuid(ddl) + "-ddl"
            embedding = self.embed(ddl)
            embedding_str = self.to_pgvector_str(embedding)
            self.cursor.execute(
                f"INSERT INTO ddl_store_{self.name_vector} (id, question, content, training_data_type, embedding) VALUES (%s, %s, %s, %s, %s::vector)",
                (id, None, ddl, 'ddl', embedding_str)
            )
            self.conn.commit()
            return id
        except psycopg2.Error as e:
            self.conn.rollback()
            raise Exception(f"Failed to add DDL: {e}")

    def add_documentation(self, documentation: str, **kwargs) -> str:
        try:
            id = deterministic_uuid(documentation) + "-doc"
            embedding = self.embed(documentation)
            embedding_str = self.to_pgvector_str(embedding)
            self.cursor.execute(
                f"INSERT INTO documentation_store_{self.name_vector} (id, question, content, training_data_type, embedding) VALUES (%s, %s, %s, %s, %s::vector)",
                (id, None, documentation, 'documentation', embedding_str)
            )
            self.conn.commit()
            return id
        except psycopg2.Error as e:
            self.conn.rollback()
            raise Exception(f"Failed to add documentation: {e}")

    def add_question_sql(self, question: str, sql: str, **kwargs) -> str:
        try:
            question_sql_json = json.dumps({"question": question, "sql": sql}, ensure_ascii=False)
            id = deterministic_uuid(question_sql_json) + "-sql"
            embedding = self.embed(question_sql_json)
            embedding_str = self.to_pgvector_str(embedding)
            self.cursor.execute(
                f"INSERT INTO question_sql_store_{self.name_vector} (id, question, content, training_data_type, embedding) VALUES (%s, %s, %s, %s, %s::vector)",
                (id, question, sql, 'sql', embedding_str)
            )
            self.conn.commit()
            return id
        except psycopg2.Error as e:
            self.conn.rollback()
            raise Exception(f"Failed to add question-SQL pair: {e}")

    def get_related_ddl(self, question: str, **kwargs) -> list:
        try:
            embedding = self.embed(question)
            embedding_str = self.to_pgvector_str(embedding)
            self.cursor.execute(
                f"SELECT content FROM ddl_store_{self.name_vector} ORDER BY embedding <=> %s LIMIT %s",
                (embedding_str, self.n_results_ddl)
            )
            return [row[0] for row in self.cursor.fetchall()]
        except psycopg2.Error as e:
            raise Exception(f"Failed to retrieve related DDL: {e}")

    def get_related_documentation(self, question: str, **kwargs) -> list:
        try:
            embedding = self.embed(question)
            embedding_str = self.to_pgvector_str(embedding)
            self.cursor.execute(
                f"SELECT content FROM documentation_store_{self.name_vector} ORDER BY embedding <=> %s LIMIT %s",
                (embedding_str, self.n_results_documentation)
            )
            return [row[0] for row in self.cursor.fetchall()]
        except psycopg2.Error as e:
            raise Exception(f"Failed to retrieve related documentation: {e}")

    def get_similar_question_sql(self, question: str, **kwargs) -> list:
        try:
            embedding = self.embed(question)
            embedding_str = self.to_pgvector_str(embedding)
            self.cursor.execute(
                f"SELECT content FROM question_sql_store_{self.name_vector} ORDER BY embedding <=> %s LIMIT %s",
                (embedding_str, self.n_results_sql)
            )
            results = self.cursor.fetchall()
            documents = []
            for row in results:
                try:
                    doc = json.loads(row[0])
                    documents.append(doc)
                except json.JSONDecodeError:
                    documents.append(row[0])
            return documents
        except psycopg2.Error as e:
            raise Exception(f"Failed to retrieve similar question-SQL pairs: {e}")

    def get_training_data(self, **kwargs) -> pd.DataFrame:
        try:
            self.cursor.execute(f"""
                SELECT id, question, content, training_data_type
                FROM ddl_store_{self.name_vector}
                UNION ALL
                SELECT id, question, content, training_data_type
                FROM documentation_store_{self.name_vector}
                UNION ALL
                SELECT id, question, content, training_data_type
                FROM question_sql_store_{self.name_vector}
            """)
            rows = self.cursor.fetchall()
            return pd.DataFrame(rows, columns=["id", "question", "content", "training_data_type"])
        except psycopg2.Error as e:
            raise Exception(f"Failed to retrieve training data: {e}")

    def remove_training_data(self, id: str, **kwargs) -> bool:
        try:
            if id.endswith("-sql"):
                self.cursor.execute(
                    f"DELETE FROM question_sql_store_{self.name_vector} WHERE id = %s",
                    (id,)
                )
            elif id.endswith("-ddl"):
                self.cursor.execute(
                    f"DELETE FROM ddl_store_{self.name_vector} WHERE id = %s",
                    (id,)
                )
            elif id.endswith("-doc"):
                self.cursor.execute(
                    f"DELETE FROM documentation_store_{self.name_vector} WHERE id = %s",
                    (id,)
                )
            else:
                return False
            self.conn.commit()
            return self.cursor.rowcount > 0
        except psycopg2.Error as e:
            self.conn.rollback()
            raise Exception(f"Failed to remove training data: {e}")

    def remove_collection(self, collection_name: str) -> bool:
        try:
            if collection_name == "sql":
                self.cursor.execute(f"DROP TABLE IF EXISTS question_sql_store_{self.name_vector}")
                self.cursor.execute(f"""
                    CREATE TABLE question_sql_store_{self.name_vector} (
                        id TEXT PRIMARY KEY,
                        question TEXT,
                        content TEXT NOT NULL,
                        training_data_type TEXT NOT NULL,
                        embedding vector(1536) NOT NULL
                    );
                """)
            elif collection_name == "ddl":
                self.cursor.execute(f"DROP TABLE IF EXISTS ddl_store_{self.name_vector}")
                self.cursor.execute(f"""
                    CREATE TABLE ddl_store_{self.name_vector} (
                        id TEXT PRIMARY KEY,
                        question TEXT,
                        content TEXT NOT NULL,
                        training_data_type TEXT NOT NULL,
                        embedding vector(1536) NOT NULL
                    );
                """)
            elif collection_name == "documentation":
                self.cursor.execute(f"DROP TABLE IF EXISTS documentation_store_{self.name_vector}")
                self.cursor.execute(f"""
                    CREATE TABLE documentation_store_{self.name_vector} (
                        id TEXT PRIMARY KEY,
                        question TEXT,
                        content TEXT NOT NULL,
                        training_data_type TEXT NOT NULL,
                        embedding vector(1536) NOT NULL
                    );
                """)
            else:
                return False
            self.conn.commit()
            self._create_indexes()
            return True
        except psycopg2.Error as e:
            self.conn.rollback()
            raise Exception(f"Failed to remove collection: {e}")

    def _ensure_tables_exist(self):
        try:
            self.cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

            self.cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS ddl_store_{self.name_vector} (
                    id TEXT PRIMARY KEY,
                    question TEXT,
                    content TEXT NOT NULL,
                    training_data_type TEXT NOT NULL,
                    embedding vector(1536) NOT NULL
                );
            """)

            self.cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS documentation_store_{self.name_vector} (
                    id TEXT PRIMARY KEY,
                    question TEXT,
                    content TEXT NOT NULL,
                    training_data_type TEXT NOT NULL,
                    embedding vector(1536) NOT NULL
                );
            """)

            self.cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS question_sql_store_{self.name_vector} (
                    id TEXT PRIMARY KEY,
                    question TEXT,
                    content TEXT NOT NULL,
                    training_data_type TEXT NOT NULL,
                    embedding vector(1536) NOT NULL
                );
            """)
            self.conn.commit()
        except psycopg2.Error as e:
            self.conn.rollback()
            raise Exception(f"Failed to create tables: {e}")

    def _create_indexes(self):
        try:
            self.cursor.execute(f"""
                CREATE INDEX IF NOT EXISTS idx_ddl_store_{self.name_vector}_embedding
                ON ddl_store_{self.name_vector} USING hnsw (embedding vector_cosine_ops);
            """)
            self.cursor.execute(f"""
                CREATE INDEX IF NOT EXISTS idx_doc_store_{self.name_vector}_embedding
                ON documentation_store_{self.name_vector} USING hnsw (embedding vector_cosine_ops);
            """)
            self.cursor.execute(f"""
                CREATE INDEX IF NOT EXISTS idx_question_sql_store_{self.name_vector}_embedding
                ON question_sql_store_{self.name_vector} USING hnsw (embedding vector_cosine_ops);
            """)
            self.conn.commit()
        except psycopg2.Error as e:
            self.conn.rollback()
            raise Exception(f"Failed to create indexes: {e}")

class MyVanna(PGvectorCustomVectorDB, OpenAI_Chat):
    def __init__(self, config=None):
        PGvectorCustomVectorDB.__init__(self, config=config, name_vector='vanna_ia_prod')
        OpenAI_Chat.__init__(self, config=config)

def VannaConfig():
    try:
        vn = MyVanna(config={
            'api_key': os.environ.get('OPENAI_API_KEY'),
            'model': 'gpt-4o-mini',
        })
        vn.connect_to_oracle(
            dsn=os.environ.get('ORACLE_DSN'),
            user=os.environ.get('ORACLE_USER'),
            password=os.environ.get('ORACLE_PASSWORD')
        )
        return vn
    except Exception as e:
        raise Exception(f"Failed to configure Vanna: {e}")`
