### ISSUE TITLE
TypeError when running `vn.ask()`

### ISSUE THREAD

**Issue by westerleyy** [vanna-ai/vanna#68]
Encountered the following error when saving the outputs of `vn.ask()` to four objects (query, df, plot, qns):
![image](https://github.com/vanna-ai/vanna-py/assets/47231787/368dca07-b262-4b6c-9f7b-fa30df7d4f7c)

This error does not appear if the parameter `print_results = False` is passed.

**Comment by zainhoda** [comment]
Intended behavior
